### ISSUE TITLE
transaction title UI issue

### ISSUE THREAD

**Issue by Mr-CodeBin** [yaviral17/paysa#1]
Bug:
In GroupPage.dart , the TransactionBubble widget is having UI issue as it's not responsive.

hint: TransactionBubble widget can be found in TransactionBubble.dart 

path:
lib\Views\Chats\TransactionBubble.dart

![image](https://github.com/yaviral17/paysa/assets/109690866/ea3eb56f-456c-41c3-b3d7-587ef54a9721)

**Comment by yaviral17** [comment]
This code in not being maintained anymore as the backend schema is changed and I have a different plan about splits functionality .

**Comment by yaviral17** [comment]
close this issue as not planned
