### ISSUE TITLE
A good documentation attracts developers

### ISSUE THREAD

**Issue by yaviral17** [yaviral17/paysa#10]
We need to update our readme in a most detailed way to make it easy for new contributors understand this project
 .

**Comment by Amitkumarkoli** [comment]
I want to help u for this .

can u explain little bit more about this application?
It has any different features than splitwize?

**Comment by yaviral17** [comment]
Hello @Amitkumarkoli , I really appreciate your interest, in this application we are aiming to provide more simplicity to users so whenever there's a split made it automatically makes a session between the paid By user and rest present in the split , to avoid the issue of calculating the amount of owe/lend of users who are common in different splits ,

For now it has manual split creation but I am aiming to add the feature to Directy create a split just by adding the bill picture. 

Also integrating an AI model that will have the access to analyse the stats of user and will help them accordingly by suggesting sub good practices they need to save more or whatever they promt to the AI.

Also, we don't have a logo for the app for now but it'll be soon done .

**Comment by Amitkumarkoli** [comment]
ok I will work on this , I takes few days so u can assign it to me.
and once u have its logo, I will add it for u if u want .
